version: '3.8'

services:
  conta-corrente-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: conta-corrente-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
